version: '3.9'
services:
  database:
    container_name: voting_database
    image: postgres:latest
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data
